// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqwdhjqleoifkqgalavk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxd2RoanFsZW9pZmtxZ2FsYXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTM1NDAsImV4cCI6MjA2NDI4OTU0MH0.tf48fLmk6HsYypJfMEy8bC7EFAQWpO2YGxRNLZCiVbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);